### ISSUE TITLE
莉 (U+8389) appears to be missing from the stroke input font

### ISSUE THREAD

**Issue by Greenactivist** [stroke-input/stroke-input-font#1]
I have the latest FDroid version of stroke-input for some reason I cannot use it to access the character 莉.  This does not look like a stroke data issue as the value in codepoint-character-sequence.txt: (122|1212|2112)3123422 looks correct.  However after using this input I only get the choice of 䔣 or 䔧.  Maybe the glyph 莉  (U+8389)	is missing from your font.

**Comment by yawnoc** [comment]
This font is only used for the keyboard proper, not the candidates bar. And even in the case of missing glyphs, it would fall back to the default Android font.

The stroke sequence for 莉 was fixed a couple of days ago in v0.9.19 of stroke-input-android; see the [changelog](https://github.com/stroke-input/stroke-input-android/blob/master/CHANGELOG.md). It was recorded with the strokes of 莈 by mistake.

F-Droid releases usually lag a week behind (the time it takes to detect the tagged release, build from source, then get someone from F-Droid to sign the apk on an airgapped machine).

**Comment by Greenactivist** [comment]
Thanks for the explanation.  I look forward to the new version.
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



4 Aug 2022, 3:42 pm by ***@***.***:
